image: docker:latest
services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_IMAGE_VERSION: "vgarcia96/docker:parking-detector-1.1.0"

docker-build:
  stage: build
  tags:
    - build
  script:
    - docker build --build-arg USER=parking -t $DOCKER_IMAGE_VERSION .

docker-push:
  stage: build
  tags: 
    - build
  script:
    - docker login
    - docker push $DOCKER_IMAGE_VERSION