version: "3"
networks:
  parking_parking:
    external: true
services:
  detector:
    image: vgarcia96/docker:parking-detector-1.1.0
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        USER: "parking"  
    environment:
      - DISPLAY
      - KAFKA_SERVER=192.168.0.60
      - KAFKA_PORT=29092
    network_mode: "host"
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    entrypoint: ["python3", "main.py", "-p", "B", "-z", "gatv", "--kafka"]
  zookeeper:
    image: bitnami/zookeeper:3.6.1
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    tmpfs: "/datalog"
    networks:
      - parking_parking
  kafka:
    image: bitnami/kafka:2.4.0
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://192.168.0.60:29092
    depends_on:
      - zookeeper
    networks:
      - parking_parking
    healthcheck:
      test:
        ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181"]
      interval: 30s
      timeout: 10s
      retries: 4
    restart: on-failure
  kafdrop:
    image: obsidiandynamics/kafdrop:3.26.0
    restart: "no"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    networks:
        - parking_parking
    ports:
      - "9000:9000"
    depends_on: 
      - kafka
    restart: on-failure
    

