redis:
    host: "localhost"
    port: 6379
    db: 0
    server_sleep: 0.25
    client_sleep: 0.25

image:
    queue: "image_queue"
    batch: 32
    dtype: "float32"
    height: 256
    width: 256
    channels: 3
    
