parking:
    zone: uk
    id: UK1

video:
    video_path: 'rtsp://carparkx:V1si0n4@10.255.33.36:8003/video'
    cam: 1
    fps_rate: 5
    mean_images: 10
    threshold: 0.1
    queue_size: 10

files:
    points: 'points/uk/zones_UK1.csv'
    model_arch:  'models/10_10-18_00/model_architecture.json'
    model_weights: 'models/10_10-18_00/model_weights.h5py'
    img_dirpath: 'images/'
    web_img_dirpath: 'web_images/'
