parking:
    zone: india
    id: IN1

video:
    video_path: 'http://root:w3p4rk@192.168.0.151/mjpg/video.mjpg'
    cam: 1
    fps_rate: 5
    mean_images: 10
    threshold: 0.1
    queue_size: 10

files:
    points: 'points/india/zones_IN1.csv'
    model_arch:  'models/10_10-18_00/model_architecture.json'
    model_weights: 'models/10_10-18_00/model_weights.h5py'
    img_dirpath: 'images/'
    web_img_dirpath: 'web_images/'
